development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # url: redis://localhost:6379/1
  url: redis://redistogo:944040daa0416e9cc55290c26487bef7@greeneye.redistogo.com:11134/
 
